
OBJ = "obj"
BB = "<<"
FF = ">>"
STREAM = "stream"
ENDSTREAM="endstream"
ENDOBJ = "endobj"
EMPTY = "empty"
PDF_FIRSTLINE = "pdf-firstline"
OBJ_META = "obj-meta"
OBJ_META_CONT = "obj-meta-cont"
OBJ_STREAM = "obj-stream"
STREAM_START = "stream-start"
STREAM_END = "stream-end"
TRAILER = "trailer"
UNKOWN = "unknown"
